#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /run

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

ip link set lo up
ip link set eth0 up
ip addr add 192.168.1.3/24 dev eth0
ip route add default via 192.168.1.1

echo "nameserver 192.168.1.1" > /etc/resolv.conf

dropbearkey -t ed25519 -f /etc/dropbear_ed25519_host_key
dropbear -s -g -r /etc/dropbear_ed25519_host_key

/bin/sh
sleep infinity 
